/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_pludov_io_JRawLib */

#ifndef _Included_fr_pludov_io_JRawLib
#define _Included_fr_pludov_io_JRawLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_pludov_io_JRawLib
 * Method:    doLoad
 * Signature: ([B)[C
 */
JNIEXPORT jcharArray JNICALL Java_fr_pludov_io_JRawLib_doLoad
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
